services:

  # Redis
  redis:
    image: redis:7-alpine
    hostname: "Redis_BJU"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - red_bju


  db:
    image: mysql:9.3
    ports:
      - "3307:3306"
    container_name: wizis_db
    hostname: "wizis_db"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD_ROOT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db:/var/lib/mysql # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 60s
      retries: 20
      start_period: 30s
    networks:
      - red_bju

  web:
    build: .
    container_name: Wizis_web
    ports:
    - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      - DEBUG=${DEBUG}
      - PYTHONUNBUFFERED=1 #Para ver los logs en tiempo real
    volumes:
      - .:/BJU:z

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthy/"]
      interval: 60s
      retries: 5
      start_period: 30s
    
    networks:
      - red_bju

  # Celery Worker
  celery:
    build: .
    command: celery -A config worker --loglevel=debug
    volumes:
      - .:/BJU:z #z es para indicarle a SELinux que etiquete los archivos para que los Contenedores accedan a ellos
    environment:
      - BJU_SETTINGS_MODULE=config.settings
      - CELERY_BROKER_URL=redis://redis:6379/0          # ← Nombre del servicio
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
        web:
          condition: service_healthy
    networks:
      - red_bju

  # ngrok:
  #   image: ngrok/ngrok:latest
  #   depends_on:
  #     web:
  #       condition: service_healthy
  #   ports:
  #     - 4040:4040 # puerto para ingresar al dashboard
  #   environment:
  #     NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  #   command: 
  #     - "http"
  #     - "http://host.docker.internal:8000"
    

volumes:
  db:
  redis_data:

networks:
  red_bju:
    driver: bridge
