"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys

from dotenv import load_dotenv
import dj_database_url

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!=k^4i&)c5)osl35s&4=#iqy@uvqd7a%kd#e-gt@_7b(y8k-%)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if os.getenv("DEBUG").lower().__eq__("true") else False

ALLOWED_HOSTS = ['*', "bju-production.up.railway.app"]

# No se como funciona o por que esta aqui, pero hay que averiguar >:v
CSRF_TRUSTED_ORIGINS = ["https://bju-production.up.railway.app"]

# Application definition

# # Agregar la carpeta applications al Python path
# sys.path.insert(0, os.path.join(BASE_DIR, 'applications'))


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'whitenoise.runserver_nostatic',

    # app de pruebas
    'apl',

    # tags personalizados y vistas base
    'applications.common',

    # apps del proyecto
    'applications.carrito_compras',
    'applications.usuarios',
    'applications.envios',
    'applications.productos',
    'applications.login',
    'applications.epayco',
    'applications.tienda',

]

AUTH_USER_MODEL = 'usuarios.Usuario'
# Urls de autenticacion
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = 'pagina_principal'
LOGOUT_REDIRECT_URL = 'pagina_principal'
AUTHENTICATION_BACKENDS = [
    'applications.usuarios.backends.EmailOUsernameBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR/'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(default=os.getenv("MYSQL_URL"))
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

# Habilitar internacionalización
USE_I18N = True

# Habilitar localización (formatos de fecha, número, etc.)
USE_L10N = True

# Usar zona horaria (recomendado mantener en True)
USE_TZ = True

# Formato de la fecha
DATE_FORMAT = 'd/m/Y'
DATETIME_FORMAT = 'd/m/Y H:i:s'
SHORT_DATE_FORMAT = 'd/m/Y'

"""
aplicacion en las plantillas
<!-- En tus templates -->
{{ fecha|date:"d/m/Y" }}
{{ fecha_hora|date:"d/m/Y H:i:s" }}

<!-- O usando la configuración por defecto -->
{{ fecha|date }}
"""

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración adicional de whitenoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# WHITENOISE_ROOT = MEDIA_ROOT

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Configuración de email
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True if os.getenv('EMAIL_USE_TLS') == 'True' else False
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# # Para desarrollo
# if DEBUG:
#     EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Configuracion para Celery

# URL del broker (Redis en este caso)
# Redis escucha en el puerto 6379 por defecto
CELERY_BROKER_URL =  os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Dónde guardar los resultados de las tareas
# También usamos Redis para esto
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Formato de serialización (cómo se convierten los datos)
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = os.getenv("CELERY_TASK_SERIALIZER")
CELERY_RESULT_SERIALIZER = os.getenv("CELERY_RESULT_SERIALIZER")

# Usar timezone aware (importante para tareas programadas)
CELERY_TIMEZONE = os.getenv("CELERY_TIMEZONE")  # Tu zona horaria
CELERY_ENABLE_UTC = True if os.getenv("CELERY_ENABLE_UTC").lower() == 'true' else False

# # Configuración de tareas periódicas (opcional)
# from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
#     # Tarea que se ejecuta cada día a las 9:00 AM
#     'enviar-reporte-diario': {
#         'task': 'inventario.tasks.generar_reporte_diario',
#         'schedule': crontab(hour=9, minute=0),
#     },
#     # Tarea que se ejecuta cada 30 minutos
#     'limpiar-cache': {
#         'task': 'core.tasks.limpiar_cache',
#         'schedule': 30 * 60,  # 30 minutos en segundos
#     },
# }

# Configuración general
SITE_NAME = 'BOX JEANS URBAN'